# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
  - go mod vendor
snapcrafts:
- id: scuttle
  builds:
    - scuttle
  name: scuttle
  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  replacements:
    amd64: 64-bit
    386: 32-bit
    darwin: macOS
  publish: false
  summary: Software to help keep secrets on GCP
  description: |
    Scuttle aims to help you prevent security breaches by keeping secrets out of
    SCM in plain text by using GCP KMS and IAM
  grade: devel
  license: GPLv3
  base: core18
  confinement: classic
builds:
- env:
  - CGO_ENABLED=0
  - GOROOT=/usr/local/go
  ignore:
  - goos: linux
    goarch: 386
  - goos: darwin
    goarch: 386
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
