name: sctl
version: git
summary: A secrets management tool
description: |
  Scuttle aims to help you prevent security breaches by keeping secrets out of
  SCM in plain text by using GCP KMS and IAM
confinement: strict
base: core18
parts:
  sctl:
    plugin: go
    go-channel: "latest/stable"
    go-importpath: github.com/vapor-ware/sctl
    source: .
    source-type: git
    build-packages:
      - gcc
apps:
  sctl:
    command: sctl
    plugs:
      - home
      - network
      - removeable-media
